### ISSUE TITLE
Tag/release the repo?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/xcub-moveit2#25]
@martinaxgloria @Nicogene we still have a run dependencies that does not have releases/tags, however we could tag the repo to start capture the version of the repo that have been relatively without a lot of changes in January/February 2024?

**Comment by Nicogene** [comment]
Here is the first tag:

- https://github.com/icub-tech-iit/xcub-moveit2/releases/tag/v0.1.0
