### ISSUE TITLE
Suggestions: use more specific package names?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/xcub-moveit2#28]
We can discuss on this in person, but I wanted to mark this down somewhere. I may be wrong, but it seems to me the CMake/ROS 2 packages installed by this repo have quite generic names (for example `robot_controller`, `robot_moveit`, `test_controller`)  that may be prone to collisions.  Such generic names are fine if they were just folders in a repo (as the name of the repo itself would result in a sort of namespace) but in this case the names are also used to install files in global location.

to avoid this problem, could it make sense to prefix all packages with `xcub_moveit2_` ? This is a common pattern in ROS repos that contain multiple ROS packages see for example:
* https://github.com/moveit/moveit2 (all packages prefixed by `moveit_`)
* https://github.com/ros-navigation/navigation2 (all packages prefixed by `nav_`)

Probably it could make sense to change this before making the repo available in the superbuild (see https://github.com/robotology/robotology-superbuild/pull/1746)?

**Comment by traversaro** [comment]
Ok for me! However, I would try to avoid names like `xcub_robot_controller` and `xcub_test_controller` that are a bit generic and do not refer to `moveit`.

**Comment by martinaxgloria** [comment]
What about `xcub_ros2_controllers`? For the test_controller package, instead, it was used to test the controller performances (see [here](https://github.com/icub-tech-iit/xcub-moveit2?tab=readme-ov-file#controller-performance)). So, if we want to avoid the name `xcub_test_controller`, we could move this folder somewhere else. 

cc @traversaro @Nicogene

**Comment by traversaro** [comment]
> What about xcub_ros2_controllers? 

Ok, it make sense as it clarify that the package contains controllers for `ros2_control`. 

> For the test_controller package, instead, it was used to test the controller performances (see [here](https://github.com/icub-tech-iit/xcub-moveit2?tab=readme-ov-file#controller-performance)). So, if we want to avoid the name xcub_test_controller, we could move this folder somewhere else.

What about `xcub_ros2_controllers_test` or `xcub_moveit_test_controller` ?

**Comment by martinaxgloria** [comment]
PR opened here:

- https://github.com/icub-tech-iit/xcub-moveit2/pull/31

cc @traversaro @Nicogene
